site_name: TerraTools
nav:
    - Home: index.md
    - About: about.md
    - TerraTools fundamentals:
        - Model interrogation: model.md
        - Physical properties: properties.md
    - Examples: reference_examples/
    - Code Reference: reference/
    - Bibliography: zz_bibliography.md

theme:
  name: "material"
  palette:
    scheme: slate

plugins:
- search
- autorefs
- section-index
- mkdocstrings:
    handlers:
        python:
            options:
                selection_opt: true
                rendering_opt: "value"
                docstring_style: "sphinx"
    watch:
    - terratools
- gen-files:
    scripts:
    - docs/gen_ref_pages.py
    - docs/copy_ref_examples.py
- literate-nav:
    nav_file: SUMMARY.md
- snippet:
        base_path: docs
- mkdocs-jupyter:
        execute: true
        allow_errors: false
        theme: dark

markdown_extensions:
    - footnotes
    - mdx_bib:
        bibtex_file: docs/references.bib
        order: sorted
    - pymdownx.snippets:
        check_paths: true
    - pymdownx.arithmatex:
        generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
