name: test


on: [push, pull_request, workflow_dispatch]

jobs:
  indent:
    name: indent
    runs-on: [ubuntu-20.04]

    strategy:
      matrix:
        python-versions: ['3.10']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-versions }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-versions }}
    - name: make indent
      run: |
        ./contrib/utilities/indent
        git diff > changes-astyle.diff
    - name: archive indent results
      uses: actions/upload-artifact@v2
      with:
        name: changes-astyle.diff
        path: changes-astyle.diff
    - name: check indentation
      run: |
        git diff --exit-code

  test:
    name: test
    runs-on: [ubuntu-20.04]

    strategy:
      matrix:
        python-versions: ['3.8', '3.9', '3.10']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-versions }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-versions }}
    - name: setup
      run: |
        # cartopy requires libgeos-dev
        sudo apt update && sudo apt install --yes \
         libgeos-dev
        python -m pip install --upgrade pip
        python --version
    - name: test
      run: |
        PYTHON=python ./test.sh